<?php
/**
 * @file
 * Checks animal scientific names and conservation statuses against IUCN data using the IUCN redlist API (http://apiv3.iucnredlist.org/). Allows updating of nodes to match this data.
 *
 */

/**
 * Implements hook_permission().
 */
function zoo_iucn_permission() {
  return array(
    'Administer Animal Data Updates via IUCN' => array(
      'title' => t('Administer Animal Data Updates via IUCN'),
    ),
  );
}

/**
 * Implements hook_help().
 */
function zoo_iucn_help($path, $arg) {
  switch ($path) {
    case 'admin/animals/data_update' :
      $h =  t("This table shows how your animal species' data compares with the most recently pulled data from IUCN. If you do not see a table below, then you must pull new data");
      return $h;
      break;
  }
}

/**
* Implements hook_flush_caches().
*/
function zoo_iucn_flush_caches() {
  return array('cache_iucn');
}

/**
 * Implements hook_menu().
 */
function zoo_iucn_menu() {
  $items = array();

  $items['admin/content/iucn'] = array(
    'title' => 'Check IUCN data',
    'description' => 'Check IUCN data',
    'page callback' => 'zoo_iucn_data_page_view',
    'file' => 'includes/zoo_iucn.controller.inc',
    'access arguments' => array('Administer Animal Data Updates via IUCN'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/content/iucn/data-view'] = array(
    'title' => 'Check IUCN data',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'access arguments' => array('Administer Animal Data Updates via IUCN'),
  );

  $items['admin/content/iucn/settings'] = array(
    'title' => 'Settings',
    'description' => 'Settings for the IUCN module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('zoo_iucn_settings_form'),
    'access arguments' => array('Administer Animal Data Updates via IUCN'),
    'file' => 'includes/zoo_iucn.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['iucn-update/%/%node'] = array(
    'page callback' => 'zoo_iucn_update_animal',
    'page arguments' => array(1, 2),
    'file' => 'includes/zoo_iucn.controller.inc',
    'access arguments' => array('Administer Animal Data Updates via IUCN'),
    // 'type' => MENU_LOCAL_TASK,
  );

  return $items;
}
